name: Publish package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build robindoc
        run: |
          pnpm run build
          cp ../../README.md .
          cp ../../LICENSE .
        working-directory: ./packages/robindoc

      - name: Build robindoc-minisearch
        run: |
          pnpm run build
          cp ../../LICENSE .
        working-directory: ./packages/robindoc-minisearch

      - name: Build robindoc-next
        run: |
          pnpm run build
          cp ../../LICENSE .
        working-directory: ./packages/robindoc-next

      - name: Build create-robindoc-app
        run: |
          pnpm run build
          cp ../../LICENSE .
        working-directory: ./packages/create-robindoc-app

      - name: Publish robindoc on main
        if: "!contains(github.ref_name, 'canary')"
        run: |
          npm set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
          npm version --no-git-tag-version ${{github.ref_name}}
          npm publish --access public
        working-directory: ./packages/robindoc

      - name: Publish robindoc on canary
        if: contains(github.ref_name, 'canary')
        run: |
          npm set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
          npm version --no-git-tag-version ${{github.ref_name}}
          npm publish --tag canary --access public
        working-directory: ./packages/robindoc

      - name: Publish robindoc-minisearch on main
        if: "!contains(github.ref_name, 'canary')"
        run: |
          npm set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
          npm version --no-git-tag-version ${{github.ref_name}}
          npm publish --access public
        working-directory: ./packages/robindoc-minisearch

      - name: Publish robindoc-minisearch on canary
        if: contains(github.ref_name, 'canary')
        run: |
          npm set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
          npm version --no-git-tag-version ${{github.ref_name}}
          npm publish --tag canary --access public
        working-directory: ./packages/robindoc-minisearch

      - name: Publish robindoc-next on main
        if: "!contains(github.ref_name, 'canary')"
        run: |
          npm set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
          npm version --no-git-tag-version ${{github.ref_name}}
          npm publish --access public
        working-directory: ./packages/robindoc-next

      - name: Publish robindoc-next on canary
        if: contains(github.ref_name, 'canary')
        run: |
          npm set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
          npm version --no-git-tag-version ${{github.ref_name}}
          npm publish --tag canary --access public
        working-directory: ./packages/robindoc-next

      - name: Publish create-robindoc-app on main
        if: "!contains(github.ref_name, 'canary')"
        run: |
          npm set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
          npm version --no-git-tag-version ${{github.ref_name}}
          npm publish --access public
        working-directory: ./packages/create-robindoc-app

      - name: Publish create-robindoc-app on canary
        if: contains(github.ref_name, 'canary')
        run: |
          npm set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
          npm version --no-git-tag-version ${{github.ref_name}}
          npm publish --tag canary --access public
        working-directory: ./packages/create-robindoc-app
